"""
graph/workflow.py — LangGraph state machine for DataNexus AI.

Workflow (Module 2):

    START
      ↓
    [classify]          ← Router: sql / etl / unknown
      ↓
    ┌─ sql ──→ [sql_agent]       ← Generate SQL via Groq
    │             ↓
    │          [validate_sql]    ← sqlglot parse + keyword check
    │           ↙         ↘
    │       invalid        valid
    │          ↓             ↓
    │    [handle_error]  [execute_sql]  ← Run against PostgreSQL
    │                        ↓
    │                  [generate_answer] ← LLM explains result
    │                        ↓
    ├─ etl ──→ [handle_etl]     ← Deferred to Module 3
    └─ unknown→ [handle_error]  ← Friendly error message
                         ↓
                        END

Module 3 extension:
    Replace handle_etl node with the real ETL agent.
    The classify → handle_etl edge is already in place.

State fields:
    question         — original user question
    task_type        — "sql" | "etl" | "unknown"
    generated_sql    — LLM-generated SQL string
    sql_valid        — whether SQL passed validation
    validation_error — reason for validation failure
    query_result     — rows returned by PostgreSQL
    answer           — final natural-language answer
    error            — error message (if any step failed)
    steps            — execution trace list (shown in API response)
"""
import logging
from typing import TypedDict, List, Optional, Any

from langgraph.graph import StateGraph, START, END

from app.agents.router import classify_request
from app.agents.sql_agent import generate_sql
from app.agents.answer_generator import generate_answer
from app.tools.sql_tools import validate_sql, execute_sql

logger = logging.getLogger(__name__)


# -------------------------------------------------------------------
# Graph State
# -------------------------------------------------------------------

class GraphState(TypedDict):
    question:         str
    task_type:        str
    generated_sql:    Optional[str]
    sql_valid:        bool
    validation_error: Optional[str]
    query_result:     Optional[List[Any]]
    answer:           Optional[str]
    insight:          Optional[dict]
    error:            Optional[str]
    steps:            List[str]


# -------------------------------------------------------------------
# Node functions
# Each receives the full state and returns a dict with updated fields.
# -------------------------------------------------------------------

def node_classify(state: GraphState) -> dict:
    """Router node: classify the user's question."""
    logger.info("[STEP] Classifying request: %r", state["question"])
    task_type = classify_request(state["question"])
    steps = state["steps"] + [f"Request classified as: {task_type.upper()}"]
    return {"task_type": task_type, "steps": steps}


def node_sql_agent(state: GraphState) -> dict:
    """SQL Agent node: generate SQL from the question."""
    logger.info("[STEP] SQL Agent generating SQL...")
    sql = generate_sql(state["question"])
    steps = state["steps"] + ["SQL query generated by LLM"]
    return {"generated_sql": sql, "steps": steps}


def node_validate_sql(state: GraphState) -> dict:
    """Validation node: check the generated SQL is safe."""
    sql = state.get("generated_sql", "")
    logger.info("[STEP] Validating SQL: %r", sql)

    # First check: LLM said it cannot generate
    if sql == "CANNOT_GENERATE" or not sql:
        steps = state["steps"] + ["SQL generation failed (CANNOT_GENERATE)"]
        logger.warning("[STEP] SQL Agent refused/failed to generate SQL.")
        return {
            "sql_valid": False,
            "validation_error": "CANNOT_GENERATE",
            "steps": steps,
        }

    if sql == "CANNOT_GENERATE_AUTH":
        steps = state["steps"] + ["SQL generation failed (Security block on auth tables)"]
        logger.warning("[STEP] SQL Agent blocked query for authentication data.")
        return {
            "sql_valid": False,
            "validation_error": "CANNOT_GENERATE_AUTH",
            "steps": steps,
        }

    # Second check: LLM flagged the request as ambiguous
    if sql.startswith("CLARIFICATION_NEEDED"):
        # Parse tables list from token: CLARIFICATION_NEEDED:users,rides,...
        parts = sql.split(":", 1)
        tables_str = parts[1].strip() if len(parts) > 1 else "users,vehicles,rides,payments,ratings"
        steps = state["steps"] + ["Request is ambiguous — clarification required"]
        logger.info("[STEP] Ambiguous request — tables: %s", tables_str)
        return {
            "sql_valid": False,
            "validation_error": f"CLARIFICATION_NEEDED:{tables_str}",
            "steps": steps,
        }

    is_valid, reason = validate_sql(sql)

    if is_valid:
        steps = state["steps"] + ["SQL validation: PASSED"]
        logger.info("[STEP] SQL validation passed.")
        return {"sql_valid": True, "validation_error": None, "steps": steps}
    else:
        steps = state["steps"] + [f"SQL validation: FAILED — {reason}"]
        logger.warning("[STEP] SQL validation failed: %s", reason)
        return {"sql_valid": False, "validation_error": reason, "steps": steps}



def node_execute_sql(state: GraphState) -> dict:
    """Execution node: run the validated SQL against PostgreSQL."""
    sql = state["generated_sql"]
    logger.info("[STEP] Executing SQL against PostgreSQL...")

    success, rows, error_msg = execute_sql(sql)

    if success:
        steps = state["steps"] + [f"Database queried — {len(rows)} row(s) returned"]
        logger.info("[STEP] SQL executed successfully, %d rows.", len(rows))
        return {"query_result": rows, "error": None, "steps": steps}
    else:
        steps = state["steps"] + ["Database query failed"]
        logger.error("[STEP] SQL execution failed: %s", error_msg)
        return {"query_result": [], "error": error_msg, "steps": steps}


def node_generate_answer(state: GraphState) -> dict:
    """Answer node: turn the DB result into a structured natural-language response."""
    logger.info("[STEP] Generating natural-language answer...")
    data = state.get("query_result", [])
    sql  = state.get("generated_sql", "")

    insight_dict = generate_answer(state["question"], sql, data)
    steps  = state["steps"] + ["Natural-language answer generated"]
    logger.info("[STEP] Answer generated.")
    return {"insight": insight_dict, "steps": steps}


def node_handle_etl(state: GraphState) -> dict:
    """ETL node: directs the user to POST /api/etl/upload (Module 3 endpoint)."""
    logger.info("[STEP] ETL request received via chat — redirecting to upload endpoint.")
    steps = state["steps"] + ["ETL request identified — redirecting to /api/etl/upload"]
    return {
        "answer": (
            "This looks like an ETL / data-processing request. "
            "To process a CSV file, use the dedicated ETL endpoint:\n\n"
            "  POST /api/etl/upload\n\n"
            "Attach your CSV file and optionally include instructions such as:\n"
            "  'Remove duplicates and handle missing values'\n"
            "  'Normalize column names and load into PostgreSQL'\n\n"
            "You can try it directly in the Swagger UI at http://localhost:8000/docs"
        ),
        "error": None,
        "steps": steps,
    }


def node_handle_error(state: GraphState) -> dict:
    """Error node: builds a user-friendly error message, differentiated by error type."""
    validation_error = state.get("validation_error", "")
    exec_error       = state.get("error")
    task_type        = state.get("task_type", "unknown")

    # Ambiguous request — needs clarification (frontend will show buttons)
    if validation_error and validation_error.startswith("CLARIFICATION_NEEDED:"):
        message = validation_error  # passed through as-is; frontend detects the prefix
    # Security block — auth queries
    elif validation_error == "CANNOT_GENERATE_AUTH":
        message = "I can't provide authentication credentials or password hashes. I can help you analyze the available business data instead."
    # SQL generation failure
    elif validation_error == "CANNOT_GENERATE":
        message = "CANNOT_GENERATE: I couldn't determine which data you're asking about. Try being more specific, e.g. 'Show all users' or 'What is the total revenue?'"
    # Security block — destructive SQL
    elif validation_error and any(kw in validation_error.lower() for kw in
                                  ["drop", "delete", "update", "insert", "alter", "truncate", "unsafe", "blocked", "dangerous"]):
        message = "UNSAFE: This operation isn't allowed. DataNexus AI only permits safe read-only analytics on the database."
    # Other validation failure
    elif validation_error:
        message = f"INVALID: {validation_error}"
    # DB execution error
    elif exec_error:
        message = f"DB_ERROR: The database query could not be completed. {exec_error}"
    # Unknown task type
    elif task_type == "unknown":
        message = "UNKNOWN: I couldn't understand that request. Please ask a question about your data, such as 'What is the total revenue?' or 'Show all users'."
    else:
        message = "SYSTEM_ERROR: An unexpected error occurred. Please try rephrasing your request."

    steps = state["steps"] + ["Request could not be completed"]
    logger.info("[STEP] Error handled: %s", message[:80])
    return {"answer": message, "steps": steps}



# -------------------------------------------------------------------
# Conditional edge functions
# -------------------------------------------------------------------

def route_after_classify(state: GraphState) -> str:
    """Routes based on task_type after classification."""
    task_type = state.get("task_type", "unknown")
    if task_type == "sql":
        return "sql"
    elif task_type == "etl":
        return "etl"
    else:
        return "error"


def route_after_validation(state: GraphState) -> str:
    """Routes to execution or error based on SQL validation result."""
    return "valid" if state.get("sql_valid") else "invalid"


def route_after_execution(state: GraphState) -> str:
    """Routes to answer generation or error based on execution result."""
    if state.get("error"):
        return "error"
    return "success"


# -------------------------------------------------------------------
# Build and compile the LangGraph
# -------------------------------------------------------------------

def build_graph() -> Any:
    """Builds and compiles the DataNexus AI LangGraph workflow."""
    graph = StateGraph(GraphState)

    # Register nodes
    graph.add_node("classify",         node_classify)
    graph.add_node("sql_agent",        node_sql_agent)
    graph.add_node("validate_sql",     node_validate_sql)
    graph.add_node("execute_sql",      node_execute_sql)
    graph.add_node("generate_answer",  node_generate_answer)
    graph.add_node("handle_etl",       node_handle_etl)
    graph.add_node("handle_error",     node_handle_error)

    # Entry point
    graph.add_edge(START, "classify")

    # After classification: route to sql_agent, handle_etl, or handle_error
    graph.add_conditional_edges(
        "classify",
        route_after_classify,
        {"sql": "sql_agent", "etl": "handle_etl", "error": "handle_error"},
    )

    # SQL flow
    graph.add_edge("sql_agent", "validate_sql")
    graph.add_conditional_edges(
        "validate_sql",
        route_after_validation,
        {"valid": "execute_sql", "invalid": "handle_error"},
    )
    graph.add_conditional_edges(
        "execute_sql",
        route_after_execution,
        {"success": "generate_answer", "error": "handle_error"},
    )

    # Terminal nodes
    graph.add_edge("generate_answer", END)
    graph.add_edge("handle_etl",      END)
    graph.add_edge("handle_error",    END)

    return graph.compile()


# Compile once at import time — reused for every request
datanexus_graph = build_graph()


def run_workflow(question: str) -> GraphState:
    """
    Entry point: run the full LangGraph workflow for a given question.

    Returns the final GraphState containing answer, sql, data, steps, etc.
    """
    initial_state: GraphState = {
        "question":         question,
        "task_type":        "",
        "generated_sql":    None,
        "sql_valid":        False,
        "validation_error": None,
        "query_result":     None,
        "answer":           None,
        "insight":          None,
        "error":            None,
        "steps":            ["Request received"],
    }

    logger.info("Starting LangGraph workflow for: %r", question)
    final_state = datanexus_graph.invoke(initial_state)
    logger.info("Workflow complete. Steps: %s", final_state.get("steps"))
    return final_state
